version: '3.1'
services:
  aidbox-db:
    image: "aidbox/db:${IMAGE_TAG}"
    ports:
      - "5444:5432"
    volumes:
    - "./pgdata:/data"
    environment:
      POSTGRES_USER:     "mostgres"
      POSTGRES_PASSWORD: "mostgres"
      POSTGRES_DB:       "devbox"
